### ISSUE TITLE
Error nginx on mount file

### ISSUE THREAD

**Issue by aukfood** [RocketChat/federation-airgap#4]
Hello, when I try to start podman-compose nginx is failed 
```
2023/10/11 08:51:40 [crit] 1#1: pread() "/etc/nginx/conf.d/rocketchat.conf" failed (21: Is a directory)
nginx: [crit] pread() "/etc/nginx/conf.d/rocketchat.conf" failed (21: Is a directory)
```

podman-compose (generated by install.sh) 
```
  proxy:
    image: ${NGINX_IMAGE}
    container_name: ${NGINX_CONTAINER}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${DOMAIN_CERTIFICATE_PATH}:/tls/${DOMAIN}.pem:z,ro
      - ${DOMAIN_KEY_PATH}:/tls/${DOMAIN}.key:z,ro
      - ./conf/nginx.conf:/etc/nginx/conf.d/rocketchat.conf:z,ro
```

A problem in mount file ?

Regards
